### ISSUE TITLE
[REQUEST] Option to disable Infinite Scroll

### ISSUE THREAD

**Issue by Erwinstein** [nurupo/chrome-mouse-wheel-tab-scroller#1]
Hey, thanks for this tiny tool you wrote. It was very useful to me too, as I also find it disappointing that the mouse wheel tab change feature on Linux was not on Windows. One thing I noticed though is that as I remember, Chrome on Linux does not change tabs infinitely (that is, when at the last tab and scrolled further, it would not loop back to the first tab) and was thinking if it is possible to do. I checked your script and although I don't understand the part of checking if the mouse is in Chrome's tab area, the part where you emulate CTRL + PG UP/PG DN is very straightforward, though with that approach, there is no way to check if you are already in the last tab/first tab and stop changing tab if it is, so this maybe a bit impossible to do. Thanks for sharing your thoughts in this.

EDIT: This was just a very minor thing though, and if was impossible then there's nothing we can't do.

**Comment by nurupo** [comment]
I was thinking of a way to fix this too, but I can't think of anything. There doesn't seem to be a way to determine if we are on the first or the last tab, nor are there "previous tab" and "next tab" hotkeys in Chrome that don't cycle around. So it looks impossible.

> I don't understand the part of checking if the mouse is in Chrome's tab area

[The first version of the script](https://github.com/nurupo/chrome-mouse-wheel-tab-scroller/blob/d5ec764cac98fb94b8fed4514a3d27c6bf8245e3/chrome-mouse-wheel-tab-scroller.au3) might be a bit easier to understand, as it didn't have support for any options so the code was smaller and simplier.

It just checks if the focused Window is Google Chrome, and if it is, if the x and y coordinates of the mouse cursor are within a rectrangular area where the browser tabs should be, size of which changes depending on whether the window is maximized or not. For example, if the Google Chrome window is maximized, then the a mouse cursor is in the tabs area if mouse's y is between 0 and 28 pixels, and x is anywhere but not the rightmost 200 pixels. 28 and 200 are hardcoded in the script. We do this check so that we send the "next tab" and "previous tab" Chrome hotkeys only when we are in Chrome window and mouse over tabs.

**Comment by Erwinstein** [comment]
Yeah, I thought so too. Maybe this was just impossible at the moment. Tried searching for other hotkeys or other ways to do it, but I can't find any.
And thanks for taking the time to explain the script. It was just that I can't understand AutoIt scripts as the reason. But when you explained it, I think I understood it a bit. Thanks.
Maybe you can close this issue while we don't have a solution for this (or leave it open, it's up to you).

**Comment by nurupo** [comment]
AutoIt is a BASIC-like language with an interesting standard library functionality. It's used primary for automation of stuff, its standard library wraps some Windows APIs like window manipulation, keyboard manipulation, mouse manipulation, creating GUIs, networking (TCP, UDP, HTTP, FTP), file system, regex, SQLite database, ini files, Windows registry, etc. It's quite rich but the code gets unwieldy pretty fast due to the language, so I wouldn't recommend writing any big project in it and limit its use just for automation scripts under 1000 lines of source code. I had a big GUI application written in it once and it was a big relief when I rewrote it in C++ using Qt for GUI, because it was getting unmanageable. Or perhaps I'm bad at using this language? In any case, I often like to think of AutoIt as bash for Windows, since it's pretty easy to scrip things in it, in contrast to the horrible Window's native batch scripting. The documentation that comes with AutoIt (press F1 when in the editor to open it) explains all functions AutoIt has and it also provides usage examples for almost every single function, and it also explains most of language constructs, like the `If ... Then ... Else ... EndIf` has its own entry i nthe documentation, so if you want to dig into it, the learning curve is very small (given you already know how to program in at least once language), all you have to do is literally look up what you want to do in the documentation using word search and just use it, or if you don't find what you want, someone might have written an AutoIt library for it, like the `MouseOnEvent.au3` that is in this repository.
