### ISSUE TITLE
Incompatible with 64-bit AutoIT?

### ISSUE THREAD

**Issue by varlokkur** [nurupo/chrome-mouse-wheel-tab-scroller#2]
Just wanted to report that I installed AutoIT and set it to default to run scripts in x64.  Running your script caused severe mouse stuttering, and after a few seconds AutoIT would crash.  However, I tried running it in x86 and it's working beautifully.  I thought I'd leave this here in case anyone else experiences the problem. 
Thanks for creating this! I missed that feature terribly.

**Comment by nurupo** [comment]
I can't think of anything in `chrome-mouse-wheel-tab-scroller.au3` that would break just because it runs on 64-bit system. It's likely an issue in the `MouseOnEvent.au3` UDF I'm using, it interacts directly with Windows API, but I have no idea what is the logic behind that script as it's a 3rd party library I'm using.

You are welcome!

**Comment by nurupo** [comment]
I have built the script as x86 and x64 and both work just fine for me on Windows 10 using the latest AutoIt 3.3.16.0. So whatever issue there was, it could have been fixed in AutoIt at some point. AutoIt still recommends building as x86, so that's the version of the exe I provide in the Releases.
