### ISSUE TITLE
About Disabling the Tray Icon

### ISSUE THREAD

**Issue by luxiangzh** [nurupo/chrome-mouse-wheel-tab-scroller#5]
I hope to add an option that allows the program to disable the tray icon. After all, this is a Chrome enhancement tool, and theoretically, once set up, it should not require manual opening or modification.

**Comment by nurupo** [comment]
Disabling tray icons is the functionality of Windows. On Windows 10, right-click on the task bar, select Taskbar Settings, then in the opened window scroll down to "Notification area" section and click on "Select which icons appear on the taskbar" -- from here you can disable any tray icon you don't want seeing, including this program's.

I will not be adding an option to disable the tray icon directly into the program as there is no need for that as you can do that via Windows and because there would be no way to enable it back, as the tray icon is the only way for a user to interact with the program. So if you want to disable the icon, just do so via the Taskbar Settings, which would also allow to enable it back if needed.

**Comment by luxiangzh** [comment]
However, in Windows 10, disabling the tray icon will not make it disappear but rather move it into the overflow area. Nonetheless, as you mentioned, since the tray icon is the only way to interact with the user, simply adding an option to hide the tray icon is not reasonable.
